### ISSUE TITLE
Mistakes Osukai as Osukan sometimes at the Earth Shrine

### ISSUE THREAD

**Issue by timharry** [mculig/TemtemTracker#12]
Farming osukai at the earth shrine sometimes detects them as Osukan. Not sure how to get logs for this

**Comment by mculig** [comment]
OCR relies on reading the text from your screen. It isn't and cannot be 100% accurate by design. Not much I can do about that.

**Comment by timharry** [comment]
Fair enough. Thank you for a great tool!
