### ISSUE TITLE
Total don't take in count Saipark luma chance

### ISSUE THREAD

**Issue by AliziaKaline** [mculig/TemtemTracker#4]
All is in the title.

![image](https://user-images.githubusercontent.com/12145066/88527626-cfe83a80-cffd-11ea-972b-4d500c02216a.png)

**Comment by mculig** [comment]
This is intended behavior. The Total acts as an unnamed Temtem with base odds and provides numbers based on that.

**Comment by AliziaKaline** [comment]
Would be cool to have the choice.
