### ISSUE TITLE
How do you calculate the "Chance Luma"?

### ISSUE THREAD

**Issue by julianpoemp** [mculig/TemtemTracker#5]
I'm thinking about the values your application is calculating. Isn't the formula to calculate the chance something like this:

> chance = 1/(8000 - x) * multiplier

where x is the number of encouters.

If I calculate it using your application with 36 Encouters and multiplier 1, I get the chance 0,45%. If I'm using my formular I get 0,1%.

**Comment by julianpoemp** [comment]
Ok, I think my formula is wrong. You calculate using this formula

> chance = encounters * (1/8000) * multiplier

that produces more realistic results than my formula. Further more if I hit the 8000 encounters the result of my formula would be undefined because division through 0 :D

**Comment by mculig** [comment]
The formula is the cumulative distribution function of the geometric distribution. https://en.wikipedia.org/wiki/Geometric_distribution

You can see it here: https://github.com/mculig/TemtemTracker/blob/master/TemtemTracker/Controllers/LumaChanceCalculator.cs#L24
