### ISSUE TITLE
Luma encounter rate changed to 1/10,000

### ISSUE THREAD

**Issue by Ninjalah** [mculig/TemtemTracker#8]
The default luma encounter rate has been changed to 1 : 10,000, and needs to be updated in the program. Thank you!

**Comment by mculig** [comment]
Done.
But in the future please consider that the evening of the day of the patch is a bit early to be creating an issue asking for an update and it comes across as a bit demanding and impatient.

**Comment by Ninjalah** [comment]
Apologies if it came off demanding, I simply made the issue when I noticed the update. Thanks for the hard work!
