### ISSUE TITLE
Toxolotl counter bug

### ISSUE THREAD

**Issue by Nahawk** [mculig/TemtemTracker#9]
Heya, this is nothing huge but kind of irritating. Sometimes, the counter counts a Toxolotl encounter as Noxolotl. It happens rarely, as seen in the picture it happened 148 times in 16,5 hours.
![Unbenanntawd](https://user-images.githubusercontent.com/77583723/104850664-afd06e80-58f0-11eb-9792-6b067216b1a3.PNG)

**Comment by mculig** [comment]
This is not a bug. Optical Character Recognition is not perfect. Depending on the resolution you're running at more or less detail is present and the chance of wrong detections is bigger or smaller.

3.67% of detections being wrong is honestly really good all things considered. Improving this is a bottomless pit of work for marginal results at best.
